server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/service1/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/service2/**